---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: migration-db-connection-creator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: migration-db-connection-creator
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: migration-db-connection-creator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: migration-db-connection-creator
subjects:
  - kind: ServiceAccount
    name: migration-db-connection-creator
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: elastic-connector-migration-db
spec:
  pipelineRef:
    name: elastic-mysql-connector-config
  params:
  - name: elastic-instance-name
    value: elasticsearch-sample
  - name: connector-id
    value: assisted-migration-db
  - name: connector-name
    value: "Assisted Migration Content"
  - name: index-name
    value: assisted-migration
  - name: secret-namespace
    value: $(context.pipelineRun.namespace)
  - name: secret-name
    value: assisted-migration-connector-config
  - name: connector-ca-certs-location
    value: "/etc/certs/ca.crt"
  taskRunSpecs:
  - pipelineTaskName: run-python-script
    serviceAccountName: migration-db-connection-creator
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
