---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust as needed
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-config
type: Opaque
stringData:
  POSTGRESQL_DATABASE: planner
  POSTGRESQL_USER: demouser
  POSTGRESQL_PASSWORD: demopass
  POSTGRESQL_MASTER_USER: admin
  POSTGRESQL_MASTER_PASSWORD: adminpass
  PGPASSWORD: adminpass
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgres
        image: quay.io/sclorg/postgresql-12-c8s:latest
        env:
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: postgres-config
              key: POSTGRESQL_DATABASE
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: postgres-config
              key: POSTGRESQL_USER
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-config
              key: POSTGRESQL_PASSWORD
        - name: POSTGRESQL_MASTER_USER
          valueFrom:
            secretKeyRef:
              name: postgres-config
              key: POSTGRESQL_MASTER_USER
        - name: POSTGRESQL_MASTER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-config
              key: POSTGRESQL_MASTER_PASSWORD
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-config
              key: PGPASSWORD
        ports:
        - containerPort: 5432
        resources:
          limits:
            cpu: 1
            memory: 2Gi
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
